from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any


YOUTUBE_SCOPES = ["https://www.googleapis.com/auth/youtube.upload"]
DEFAULT_KEY_DIR = Path(r"C:\Users\sinmb\key")
DEFAULT_CLIENT_SECRETS = DEFAULT_KEY_DIR / "youtube-client-secret.json"
DEFAULT_TOKEN_FILE = DEFAULT_KEY_DIR / "youtube-token.json"


if sys.stdout.encoding != "utf-8":
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")


def load_metadata(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def build_upload_request(metadata: dict[str, Any]) -> dict[str, Any]:
    return {
        "snippet": {
            "title": metadata["title"],
            "description": metadata["description"],
            "tags": metadata.get("tags", []),
            "categoryId": metadata.get("categoryId", "10"),
            "defaultLanguage": metadata.get("defaultLanguage", "ko"),
            "defaultAudioLanguage": metadata.get("defaultAudioLanguage", metadata.get("defaultLanguage", "ko")),
        },
        "status": {
            "privacyStatus": metadata.get("privacyStatus", "private"),
            "selfDeclaredMadeForKids": bool(metadata.get("madeForKids", False)),
        },
    }


def dry_run_upload(
    *,
    video_path: Path,
    metadata: dict[str, Any],
    thumbnail_path: Path | None = None,
) -> dict[str, Any]:
    return {
        "status": "dry_run",
        "videoPath": video_path.resolve().as_posix(),
        "thumbnailPath": thumbnail_path.resolve().as_posix() if thumbnail_path else None,
        "request": build_upload_request(metadata),
    }


def _load_credentials(client_secrets_path: Path, token_path: Path):
    from google.auth.transport.requests import Request
    from google.oauth2.credentials import Credentials
    from google_auth_oauthlib.flow import InstalledAppFlow

    creds = None
    if token_path.exists():
        creds = Credentials.from_authorized_user_file(str(token_path), YOUTUBE_SCOPES)

    if creds and creds.expired and creds.refresh_token:
        creds.refresh(Request())
        token_path.write_text(creds.to_json(), encoding="utf-8")
        return creds

    if creds and creds.valid:
        return creds

    if not client_secrets_path.exists():
        raise FileNotFoundError(
            f"Client secrets file not found: {client_secrets_path}. Place OAuth secrets under C:\\Users\\sinmb\\key."
        )

    flow = InstalledAppFlow.from_client_secrets_file(str(client_secrets_path), YOUTUBE_SCOPES)
    creds = flow.run_local_server(port=0)
    token_path.parent.mkdir(parents=True, exist_ok=True)
    token_path.write_text(creds.to_json(), encoding="utf-8")
    return creds


def upload_video(
    *,
    video_path: Path,
    metadata: dict[str, Any],
    thumbnail_path: Path | None = None,
    client_secrets_path: Path = DEFAULT_CLIENT_SECRETS,
    token_path: Path = DEFAULT_TOKEN_FILE,
    dry_run: bool = True,
) -> dict[str, Any]:
    if not video_path.exists():
        raise FileNotFoundError(f"Video file not found: {video_path}")
    if thumbnail_path is not None and not thumbnail_path.exists():
        raise FileNotFoundError(f"Thumbnail file not found: {thumbnail_path}")

    if dry_run:
        return dry_run_upload(video_path=video_path, metadata=metadata, thumbnail_path=thumbnail_path)

    from googleapiclient.discovery import build
    from googleapiclient.http import MediaFileUpload

    creds = _load_credentials(client_secrets_path, token_path)
    youtube = build("youtube", "v3", credentials=creds)

    request_body = build_upload_request(metadata)
    media = MediaFileUpload(str(video_path), mimetype="video/mp4", resumable=True, chunksize=8 * 1024 * 1024)

    insert_request = youtube.videos().insert(
        part="snippet,status",
        body=request_body,
        media_body=media,
    )
    upload_response = insert_request.execute()

    video_id = upload_response["id"]
    if thumbnail_path is not None:
        youtube.thumbnails().set(videoId=video_id, media_body=MediaFileUpload(str(thumbnail_path))).execute()

    return {
        "status": "uploaded",
        "videoId": video_id,
        "videoUrl": f"https://www.youtube.com/watch?v={video_id}",
        "thumbnailPath": thumbnail_path.resolve().as_posix() if thumbnail_path else None,
        "request": request_body,
    }


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Upload a final render to YouTube with a safe dry-run default.")
    parser.add_argument("--video", type=Path, required=True, help="Final MP4 file.")
    parser.add_argument("--metadata", type=Path, required=True, help="Metadata JSON generated by assemble_final.py.")
    parser.add_argument("--thumbnail", type=Path, default=None, help="Optional thumbnail JPG.")
    parser.add_argument("--client-secrets", type=Path, default=DEFAULT_CLIENT_SECRETS, help="OAuth client secrets path.")
    parser.add_argument("--token-file", type=Path, default=DEFAULT_TOKEN_FILE, help="OAuth token cache path.")
    parser.add_argument("--live", action="store_true", help="Perform a real upload instead of a dry run.")
    return parser


def main() -> None:
    args = build_parser().parse_args()
    metadata = load_metadata(args.metadata)
    result = upload_video(
        video_path=args.video,
        metadata=metadata,
        thumbnail_path=args.thumbnail,
        client_secrets_path=args.client_secrets,
        token_path=args.token_file,
        dry_run=not args.live,
    )
    print(json.dumps(result, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
